CC		:= cc
CFLAGS 	:= -O3 -flto
LDFLAGS := $(CFLAGS) \
-lcurl -lm
TARGET  := myapp
SRCS    := $(wildcard src9-4/*.c)
OBJS    := $(patsubst %.c,%.o,$(SRCS))
all: $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) $(LDFLAGS) -o $(TARGET) 
