CXX		:= clang++
CFLAGS 	:= -O3 -flto 
LDFLAGS := $(CFLAGS) \
-lcurl -lm
TARGET  := myapp
SRCS    := $(wildcard src3/*.cpp)
OBJS    := $(patsubst %.cpp,%.o,$(SRCS))
all: $(OBJS)
	$(CXX) $(OBJS) $(CFLAGS) $(LDFLAGS) -o $(TARGET) 
