name: 3DS-curl-v5
on:
  push:
    branches:
    - main
jobs:
  build-3ds:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile-3ds-7
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: 3ds-curl
        path: |
          *.elf
          *.3dsx
