name: 3DS-curl-v5
on:
  push:
    branches:
    - main
jobs:
  build-3ds:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Compile
      run: |
        sudo dkp-pacman -Ql
        make -f Makefile-chess-3ds-6-Book
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: 3ds-curl
        path: |
          *.3dsx
