name: DSi-curl-v1
on:
  push:
    branches:
    - main
jobs:
  build-nds:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install custom packages
      run: |
        sudo dkp-pacman -Ql 
    - name: Compile
      run: |
        make -f Makefile-DSi
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: dsi-curl
        path: |
          *.nds
    
