name: OSX-SDL2-Brew-2-TUIMarket
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile.6
    - name: Create tarball
      run: |
        tar -cvf myapp.tgz tuimarket
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Artifact
        path: |
          .
