name: Wii-curl-v1
on:
  push:
    branches:
    - main
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install wii-curl dependency
      run: |
        CURL_TAG="v7.45.0"
        CURL_FILENAME="libcurl-7.45.0_wii.tar.bz2"
        CURL_URL="https://github.com/AndrewPiroli/wii-curl/releases/download/${CURL_TAG}/${CURL_FILENAME}"
        curl -L -o ${CURL_FILENAME} ${CURL_URL}
        tar -xjf ${CURL_FILENAME} -C ${DEVKITPRO}
        rm ${CURL_FILENAME}
        ls -l ${DEVKITPRO}/portlibs/ppc/lib/libcurl.a
    - name: Compile
      run: |
        make -f Makefile-wii
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wii-curl
        path: ./wii/*.dol
