name: Wii-curl-v1
on:
  push:
    branches:
    - main
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update package database and install wii-curl
      run: |
        sudo dkp-pacman -Q
        # sudo dkp-pacman -Syu --noconfirm
        # sudo dkp-pacman -S --noconfirm --ask 4 libwiisocket wii-mbedtls wii-curl
        # sudo dkp-pacman -S libwiisocket-0.1-1-any.pkg.tar.gz --noconfirm 
        # sudo dkp-pacman -S wii-mbedtls-3.6.4-1-any.pkg.tar.gz --noconfirm 
        # sudo dkp-pacman -S wii-curl-8.16.0-1-any.pkg.tar.gz --noconfirm       
    - name: Compile
      run: |
        make -f Makefile-wii
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wii-curl
        path: |
          ./wii/*.dol
