name: Wii-curl-v1
on:
  push:
    branches:
    - main
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download custom packages
      run: |
          # Use curl with -L to follow redirects and -O to save with the original filename
          curl -L -O https://github.com/AndrewPiroli/wii-curl/releases/download/v8.16.0-1/libwiisocket-0.1-1-any.pkg.tar.gz
          curl -L -O https://github.com/AndrewPiroli/wii-curl/releases/download/v8.16.0-1/wii-mbedtls-3.6.4-1-any.pkg.tar.gz
          curl -L -O https://github.com/AndrewPiroli/wii-curl/releases/download/v8.16.0-1/wii-curl-8.16.0-1-any.pkg.tar.gz
    - name: Install custom packages
      run: |
          dkp-pacman -U --noconfirm libwiisocket-*.pkg.tar.gz wii-mbedtls-*.pkg.tar.gz wii-curl-*.pkg.tar.gz
    - name: Compile
      run: |
        make -f Makefile-wii
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wii-curl
        path: |
          ./wii/*.dol
