name: Wii-curl-v1
on:
  push:
    branches:
    - main
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update package database and install wii-curl
      run: |
          sudo dkp-pacman-key --recv-keys C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE --keyserver keyserver.ubuntu.com
          sudo dkp-pacman-key --lsign-key C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S wii-curl --noconfirm        
    - name: Compile
      run: |
        make -f Makefile-wii
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wii-curl
        path: |
          ./wii/*.dol
