name: Wii-curl-v1
on:
  push:
    branches:
    - main
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install wii-curl dependency
      run: |
        CURL_TAG="v8.16.0"
        CURL_FILENAME="libwiisocket-0.1-1-any.pkg.tar.gz"
        CURL_FILENAME2="wii-mbedtls-3.6.4-1-any.pkg.tar.gz"
        CURL_FILENAME3="wii-curl-8.16.0-1-any.pkg.tar.gz"
        CURL_URL="https://github.com/AndrewPiroli/wii-curl/releases/download/${CURL_TAG}/${CURL_FILENAME}"
        curl -L -o ${CURL_FILENAME} ${CURL_URL}
        tar -xjf ${CURL_FILENAME} -C ${DEVKITPRO}
        rm ${CURL_FILENAME}
    - name: Compile
      run: |
        make -f Makefile-wii
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wii-curl
        path: ./wii/*.dol
